### PR TITLE
major code refactoring on classes

### PR DESCRIPTION
**Pull request by chfw**
After the refactoring, the grid, timeline and overlap still shows OK:

overlap
screen shot 2017-10-15 at 17 37 28

timeline
screen shot 2017-10-15 at 17 38 04

grid
screen shot 2017-10-15 at 17 38 40

@chenjiandongx @kinegratii , please review codes, especially the class constructors(Base, Chart).

### CODE REVIEW

**Comment by chfw** [comment]
please checkout dev branch of my fork https://github.com/pyexcel-renderers/pyecharts to evaluate.

**Comment by kinegratii** [comment]
@chfw 
https://github.com/pyexcel-renderers/pyecharts/blob/ce22667441b911327a742bde42fc4a26477ac0f7/pyecharts/chart.py#L6

The `pyecharts.base` module has rename to `pyecharts.chart`,but this file still import old `base` module.Is there some errors?

And can you provide some pictures or text (e.g UML class diagram) to describe your thought about the inherit system of these chart classes?

**Comment by chenjiandongx** [comment]
@chfw 说一下我个人的看法，我觉得 Base 类好像不怎么需要重构，毕竟只维护一份就行。而 BaseCustom 其实也只是需要简单两个初始化（__init__）属性而已，好像没有必要将他们整合在一起。

**Comment by chfw** [comment]
Here is the CRP:
class-relationship-diagram

Base class is still there but Chart was taken out as it has lengthy add method. Timeline, Overlap and Grid and Chart inherits from the same Base Class, because they all use _option, js_dependencies, width, height. @chenjiandongx , I knew T, O, G had simple constructor, but those three used Class Composition, where a chart instance is an attribute and this particular chart instance is instantiated with potentially long constructor. However, what TOG is doing is to "steal" all options from the first incoming resident chart, in a sense, TOG could be initialized in the same way as it used to be.

**Comment by chfw** [comment]
With this PR, we won't have two base classes, one for chart, and the other for T.O.G. All properties, such as options, js_dependencies are aligned. And it means, any common new features for all charts can be applied in Base class, a single place.

**Comment by chenjiandongx** [comment]
@chfw 明白你的想法，但 base.py 和 chart.py 我有点建议，你这样要维护两个同样的 `__init__` 的参数。如果自定义类集成自 `Base` 的话，Base 的初始化完全可以简单点（自定义类不需要这么多初始化参数），只在 `Chart` 中初始化那些参数就行。

**Comment by chfw** [comment]
OK. Will reduce the parameters in another commit.

**Comment by chfw** [comment]
I am done. Review, please!

**Comment by chenjiandongx** [comment]
@chfw well done!

**Comment by chenjiandongx** [comment]
@chfw https://github.com/chenjiandongx/pyecharts/commit/2f040502f17c42fec8f60f9ab760a7459c95dc46

**Pull request merged**
